# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 344125f1c5b6c19cbfd60f973fb4795f2038e25f241f6d35cd44d120d587db5118f86e99735879f200d90058a2857599829065d7fc40eeaacef375c028fa21e1

test:
  secret_key_base: a313581b94bf241ceeac17f56523ccba9dafb972a2ee85ce67a5a301d1827e132a0d30f55c091d49d5c1c0670babed91dd3cf13a9469ef1321214ef10ebb3fd0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
